### ISSUE TITLE
Missing close div

### ISSUE THREAD

**Issue by gepetobio** [peoray/Todometer#1]
https://github.com/peoray/Todometer/blob/32a26f008d383bc38cfb4a8826ff38800d4aedb4/index.html#L55

There is a missing close div in this line. It's the `</div>` of the #app element. That's why there is a compiling error on the template.

![image](https://user-images.githubusercontent.com/1509314/37954076-0e904ce2-317b-11e8-836d-90e541bf5a50.png)

**Comment by peoray** [comment]
I was just wondering what the heck was wrong cause the app was still functioning well : )
