### ISSUE TITLE
Problems with your ternaries

### ISSUE THREAD

**Issue by gepetobio** [peoray/Todometer#2]
https://github.com/peoray/Todometer/blob/32a26f008d383bc38cfb4a8826ff38800d4aedb4/app.js#L49

Hi Emmanuel, the issue with your ternaries is that you are not saving the result anywhere. Try to do something like this:

```dd = dd < 10 ? `0${dd}` : `${dd}`;```

Also, you'll notice that I changed the last bit of the ternary to transform everything to a string, otherwise you'll end up with some of the variables as numbers and others (those less than 10) as strings.

**Comment by peoray** [comment]
Oh yeah, thanks. I immediately saw the mistake : ).
